### ISSUE TITLE
Unable to Build Docs on Python 3.12

### ISSUE THREAD

**Issue by thebeanogamer** [breathe-doc/breathe#933]
I'm trying to get `breathe` to build on Python 3.12 for Fedora Rawhide. However, I'm getting a C++ error whilst running `make`. This appears to be the same issue as sphinx-doc/sphinx#9433, although their solution of updating Doxygen doesn't apply as I'm already up to date (`1.9.7`).

```py
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.12/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 310, in build
    with logging.pending_warnings():
  File "/usr/lib64/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.12/site-packages/sphinx/util/logging.py", line 219, in pending_warnings
    memhandler.flushTo(logger)
  File "/usr/local/lib/python3.12/site-packages/sphinx/util/logging.py", line 184, in flushTo
    logger.handle(record)
  File "/usr/lib64/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.12/logging/__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/logging/__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sphinx/util/logging.py", line 424, in filter
    raise exc
sphinx.errors.SphinxWarning: /builddir/breathe/documentation/source/specific.rst:195:Invalid C++ declaration: Expected identifier in nested name. [error at 0]
```

I've installed all the packages from the `requirements.txt` files.

```shell
$ pip freeze
alabaster==0.7.13
Babel==2.12.1
beautifulsoup4==4.12.2
black==22.3.0
build==0.10.0
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
docutils==0.20.1
flake8==6.0.0
furo==2023.5.20
idna==3.4
imagesize==1.4.1
iniconfig==2.0.0
Jinja2==3.1.2
MarkupSafe==2.1.3
mccabe==0.7.0
mypy==1.4.0
mypy-extensions==1.0.0
packaging==23.1
pathspec==0.11.1
pip-tools==6.13.0
platformdirs==3.7.0
pluggy==1.2.0
pycodestyle==2.10.0
pyflakes==3.0.1
Pygments==2.15.1
pyproject_hooks==1.0.0
pytest==7.3.2
requests==2.31.0
snowballstemmer==2.2.0
soupsieve==2.4.1
Sphinx==7.0.1
sphinx-basic-ng==1.0.0b1
sphinx-copybutton==0.5.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
types-docutils==0.17.7
types-Pygments==2.15.0.1
types-setuptools==68.0.0.0
typing_extensions==4.6.3
urllib3==2.0.3
```

Full logs from the build can be found on <https://kojipkgs.fedoraproject.org//work/tasks/7121/102467121/build.log>.

**Comment by thebeanogamer** [comment]
After doing some more testing, I've also been able to replicate this issue with Python 3.11. Going to close this issue and raise a new one with relevant details.

**Comment by hroncok** [comment]
This seems to have started with doxygen 1.9.6 -> 1.9.7 update in Fedora.

> Going to close this issue and raise a new one with relevant details.

Have you ever?
