### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rstrip' in breathe/project.py

### ISSUE THREAD

**Issue by olivierbichler-cea** [breathe-doc/breathe#944]
Hi,

I recently got the following error during Sphinx compilation. Everything was working fine a month ago.

Python version:  3.10.12
Sphinx version: 7.2.2

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/sphinx/registry.py", line 460, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/breathe/__init__.py", line 12, in setup
    directive_setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/breathe/directives/setup.py", line 61, in setup
    project_info_factory = ProjectInfoFactory(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/breathe/project.py", line 116, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
AttributeError: 'PosixPath' object has no attribute 'rstrip'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/eclipse-aidge/envs/latest/lib/python3.10/site-packages/breathe/project.py", line 116, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```

Do you have any clue on how to solve this?
Thanks

**Comment by olivierbichler-cea** [comment]
Actually, what changed is the version of Sphinx: the issue was not occuring with Sphinx 7.1.2

**Comment by ranft** [comment]
This error is caused by a change in the sphinx API, where the `app.doctreedir` configuration now is a (pathlib.Path|str) instead of a plain string before. This is the reason, why I do create a new path object in my fix, since I can't be sure what type I actually have there.

**Comment by scottamain** [comment]
I'm also seeing this issue. Any hope for a fix in Breathe?

**Comment by scottamain** [comment]
This worked for me: https://github.com/breathe-doc/breathe/pull/964
