### ISSUE TITLE
TypeError: sequence item 0: expected str instance, PosixPath found

### ISSUE THREAD

**Issue by hwhsu1231** [breathe-doc/breathe#992]
### Problem Description

I tried to build breathe-docs by following the instruction of [.github/workflows/documentation.yml](https://github.com/breathe-doc/breathe/blob/62695c7e3eaf1190f7bb02ba7b396daf78da66f4/.github/workflows/documentation.yml) on Kubuntu. However, it failed with the following error message and prompt `(Pdb)`:

```bash
Exception occurred while building, starting debugger:  
Traceback (most recent call last):  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main  
   app = Sphinx(args.sourcedir, args.confdir, args.outputdir,  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/application.py", line 292, in __init__  
   self._init_builder()  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/application.py", line 366, in _init_builder  
   self.events.emit('builder-inited')  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/events.py", line 98, in emit  
   results.append(listener.handler(self.app, *args))  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/directives/setup.py", line 114, in doxygen_hook  
   doxygen_handle.generate_xml(  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py", line 69, in generate_xml  
   project_path = self.process(  
 File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py", line 93, in process  
   input=" ".join(full_paths),  
TypeError: sequence item 0: expected str instance, PosixPath found  
> /home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py(93)process()  
-> input=" ".join(full_paths),  
(Pdb)
```

### Versions and Environments

- OS version: Kubuntu 22.04
- Breathe version: 62695c7e3eaf1190f7bb02ba7b396daf78da66f4
- Python version: `3.10`

### Steps to Reproduce

Run the following commands in order:

```bash
git clone --branch=main --depth=1 https://github.com/breathe-doc/breathe.git
cd breathe
git show --no-patch

sudo apt-get install graphviz libclang1-11 libclang-cpp11

mkdir doxygen-bin-arc && cd doxygen-bin-arc
export DOXYGEN_VERSION=1.9.4
curl -L https://sourceforge.net/projects/doxygen/files/rel-$DOXYGEN_VERSION/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz > doxygen.tar.gz
gunzip doxygen.tar.gz
tar xf doxygen.tar
cd doxygen-$DOXYGEN_VERSION
sudo make install
which doxygen && doxygen --version

cd ../..
which python && python --version
python -m venv ./.venv
source .venv/bin/activate
python -m pip install --upgrade pip
python -m pip install .[docs]

export LANG=en_US.UTF-8
make html
```

### Logs

<details><summary>Click to expand the full logs of Steps to Reproduce</summary>

```bash
hwhsu1231@vb-kubuntu:~/Repo/testing$ git clone --branch=main --depth=1 https://github.com/breathe-doc/breathe.git
Cloning into 'breathe'...
remote: Enumerating objects: 349, done.
remote: Counting objects: 100% (349/349), done.
remote: Compressing objects: 100% (304/304), done.
remote: Total 349 (delta 100), reused 171 (delta 38), pack-reused 0
Receiving objects: 100% (349/349), 243.71 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (100/100), done.
hwhsu1231@vb-kubuntu:~/Repo/testing$ cd breathe
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ git show --no-patch
commit 62695c7e3eaf1190f7bb02ba7b396daf78da66f4 (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: Scott Main <scottamain@gmail.com>
Date:   Tue Jul 30 09:19:54 2024 -0700

    Insert signature name for use with Sphinx Table of Contents (#959)
    
    If it's a function, add parentheses to the name.
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ sudo apt-get install graphviz libclang1-11 libclang-cpp11
[sudo] password for hwhsu1231: 
正在讀取套件清單... 完成
正在重建相依關係... 完成  
正在讀取狀態資料... 完成  
libclang-cpp11 is already the newest version (1:11.1.0-6).
libclang1-11 is already the newest version (1:11.1.0-6).
graphviz is already the newest version (2.42.2-6ubuntu0.1).
升級 0 個，新安裝 0 個，移除 0 個，有 2 個未被升級。
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ mkdir doxygen-bin-arc && cd doxygen-bin-arc
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc$ export DOXYGEN_VERSION=1.9.4
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc$ curl -L https://sourceforge.net/projects/doxygen/files/rel-$DOXYGEN_VERSION/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz > doxygen.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376    0   376    0     0    942      0 --:--:-- --:--:-- --:--:--   942
100   392    0   392    0     0    320      0 --:--:--  0:00:01 --:--:--  382k
100   623    0   623    0     0    439      0 --:--:--  0:00:01 --:--:--   439
100   377  100   377    0     0    161      0  0:00:02  0:00:02 --:--:-- 22176
100 48.4M  100 48.4M    0     0  3866k      0  0:00:12  0:00:12 --:--:-- 6382k
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc$ gunzip doxygen.tar.gz
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc$ tar xf doxygen.tar
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc$ cd doxygen-$DOXYGEN_VERSION
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc/doxygen-1.9.4$ sudo make install
/usr/bin/install -d /usr/local/bin
/usr/bin/install -d /usr/local/doc/doxygen
/usr/bin/install -d /usr/local/man/man1
/usr/bin/install -m 755 bin/doxygen    /usr/local/bin
cp -r html /usr/local/doc/doxygen
cp -r examples /usr/local/doc/doxygen
cp doxygen_manual*.pdf /usr/local/doc/doxygen
cp man/man1/* /usr/local/man/man1/
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc/doxygen-1.9.4$ which doxygen && doxygen --version
/usr/local/bin/doxygen
1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe/doxygen-bin-arc/doxygen-1.9.4$ cd ../..
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ which python && python --version
/usr/bin/python
Python 3.10.12
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ python -m venv ./.venv
hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ source .venv/bin/activate
(.venv) hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ python -m pip install --upgrade pip
Requirement already satisfied: pip in ./.venv/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Using cached pip-24.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-24.2
(.venv) hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ python -m pip install .[docs]
Processing /home/hwhsu1231/Repo/testing/breathe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Sphinx>=6.2 (from breathe==4.35.0)
  Using cached sphinx-8.0.2-py3-none-any.whl.metadata (6.2 kB)
Collecting furo (from breathe==4.35.0)
  Using cached furo-2024.7.18-py3-none-any.whl.metadata (5.9 kB)
Collecting sphinx-copybutton (from breathe==4.35.0)
  Using cached sphinx_copybutton-0.5.2-py3-none-any.whl.metadata (3.2 kB)
Collecting sphinxcontrib-spelling (from breathe==4.35.0)
  Using cached sphinxcontrib_spelling-8.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting sphinxcontrib-applehelp (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-devhelp (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-jsmath (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.9 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl.metadata (2.4 kB)
Collecting sphinxcontrib-qthelp (from Sphinx>=6.2->breathe==4.35.0)
  Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting Jinja2>=3.1 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting Pygments>=2.17 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting docutils<0.22,>=0.20 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting snowballstemmer>=2.2 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting babel>=2.13 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached Babel-2.15.0-py3-none-any.whl.metadata (1.5 kB)
Collecting alabaster>=0.7.14 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached alabaster-1.0.0-py3-none-any.whl.metadata (2.8 kB)
Collecting imagesize>=1.3 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached imagesize-1.4.1-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting requests>=2.30.0 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=23.0 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting tomli>=2 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting beautifulsoup4 (from furo->breathe==4.35.0)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting Sphinx>=6.2 (from breathe==4.35.0)
  Using cached sphinx-7.4.7-py3-none-any.whl.metadata (6.1 kB)
Collecting sphinx-basic-ng>=1.0.0.beta2 (from furo->breathe==4.35.0)
  Using cached sphinx_basic_ng-1.0.0b2-py3-none-any.whl.metadata (1.5 kB)
Collecting alabaster~=0.7.14 (from Sphinx>=6.2->breathe==4.35.0)
  Using cached alabaster-0.7.16-py3-none-any.whl.metadata (2.9 kB)
Collecting PyEnchant>=3.1.1 (from sphinxcontrib-spelling->breathe==4.35.0)
  Using cached pyenchant-3.2.2-py3-none-any.whl.metadata (3.8 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1->Sphinx>=6.2->breathe==4.35.0)
  Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.30.0->Sphinx>=6.2->breathe==4.35.0)
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.30.0->Sphinx>=6.2->breathe==4.35.0)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.30.0->Sphinx>=6.2->breathe==4.35.0)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.30.0->Sphinx>=6.2->breathe==4.35.0)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->furo->breathe==4.35.0)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Using cached furo-2024.7.18-py3-none-any.whl (340 kB)
Using cached sphinx-7.4.7-py3-none-any.whl (3.4 MB)
Using cached sphinx_copybutton-0.5.2-py3-none-any.whl (13 kB)
Using cached sphinxcontrib_spelling-8.0.0-py3-none-any.whl (16 kB)
Using cached alabaster-0.7.16-py3-none-any.whl (13 kB)
Using cached Babel-2.15.0-py3-none-any.whl (9.6 MB)
Using cached docutils-0.21.2-py3-none-any.whl (587 kB)
Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pyenchant-3.2.2-py3-none-any.whl (55 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Using cached sphinx_basic_ng-1.0.0b2-py3-none-any.whl (22 kB)
Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl (92 kB)
Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)
Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Building wheels for collected packages: breathe
  Building wheel for breathe (pyproject.toml) ... done
  Created wheel for breathe: filename=breathe-4.35.0-py3-none-any.whl size=95224 sha256=cf2136ff47716f426cb0cc48aa55ddfa53f2490ee690dd0457308831c93c57f2
  Stored in directory: /tmp/pip-ephem-wheel-cache-z3mlmt2m/wheels/3a/f6/74/cb8b2b54b56a600a71f3ece13acb1ce7ba8b4779b205ce8a9d
Successfully built breathe
Installing collected packages: snowballstemmer, urllib3, tomli, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, Pygments, PyEnchant, packaging, MarkupSafe, imagesize, idna, docutils, charset-normalizer, certifi, babel, alabaster, requests, Jinja2, beautifulsoup4, Sphinx, sphinxcontrib-spelling, sphinx-copybutton, sphinx-basic-ng, breathe, furo
Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 PyEnchant-3.2.2 Pygments-2.18.0 Sphinx-7.4.7 alabaster-0.7.16 babel-2.15.0 beautifulsoup4-4.12.3 breathe-4.35.0 certifi-2024.7.4 charset-normalizer-3.3.2 docutils-0.21.2 furo-2024.7.18 idna-3.7 imagesize-1.4.1 packaging-24.1 requests-2.32.3 snowballstemmer-2.2.0 soupsieve-2.5 sphinx-basic-ng-1.0.0b2 sphinx-copybutton-0.5.2 sphinxcontrib-applehelp-2.0.0 sphinxcontrib-devhelp-2.0.0 sphinxcontrib-htmlhelp-2.1.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-2.0.0 sphinxcontrib-serializinghtml-2.0.0 sphinxcontrib-spelling-8.0.0 tomli-2.0.1 urllib3-2.2.2
(.venv) hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ export LANG=en_US.UTF-8
(.venv) hwhsu1231@vb-kubuntu:~/Repo/testing/breathe$ make html
make -C examples/doxygen all
make[1]: Entering directory '/home/hwhsu1231/Repo/testing/breathe/examples/doxygen'
`which doxygen` class.cfg
`which doxygen` concept.cfg
`which doxygen` define.cfg
`which doxygen` enum.cfg
`which doxygen` file.cfg
`which doxygen` func.cfg
`which doxygen` page.cfg
`which doxygen` relates.cfg
`which doxygen` author.cfg
`which doxygen` par.cfg
`which doxygen` parblock.cfg
`which doxygen` overload.cfg
`which doxygen` example.cfg
`which doxygen` include.cfg
`which doxygen` qtstyle.cfg
`which doxygen` jdstyle.cfg
`which doxygen` structcmd.cfg
`which doxygen` autolink.cfg
`which doxygen` restypedef.cfg
`which doxygen` afterdoc.cfg
`which doxygen` templ.cfg
`which doxygen` tag.cfg
`which doxygen` group.cfg
`which doxygen` diagrams.cfg
`which doxygen` memgrp.cfg
`which doxygen` docstring.cfg
`which doxygen` pyexample.cfg
`which doxygen` manual.cfg
`which doxygen` interface.cfg
make[1]: Leaving directory '/home/hwhsu1231/Repo/testing/breathe/examples/doxygen'
make -C examples/tinyxml all
make[1]: Entering directory '/home/hwhsu1231/Repo/testing/breathe/examples/tinyxml'
`which doxygen` tinyxml.cfg
make[1]: Leaving directory '/home/hwhsu1231/Repo/testing/breathe/examples/tinyxml'
make -C examples/specific all
make[1]: Entering directory '/home/hwhsu1231/Repo/testing/breathe/examples/specific'
`which doxygen` nutshell.cfg
`which doxygen` alias.cfg
`which doxygen` rst.cfg
`which doxygen` inline.cfg
`which doxygen` namespacefile.cfg
`which doxygen` array.cfg
`which doxygen` inheritance.cfg
`which doxygen` members.cfg
`which doxygen` userdefined.cfg
`which doxygen` fixedwidthfont.cfg
`which doxygen` latexmath.cfg
`which doxygen` functionOverload.cfg
`which doxygen` image.cfg
`which doxygen` name.cfg
`which doxygen` union.cfg
`which doxygen` group.cfg
`which doxygen` struct.cfg
`which doxygen` struct_function.cfg
`which doxygen` qtsignalsandslots.cfg
`which doxygen` lists.cfg
`which doxygen` headings.cfg
`which doxygen` links.cfg
`which doxygen` parameters.cfg
`which doxygen` template_class.cfg
`which doxygen` template_class_non_type.cfg
`which doxygen` template_function.cfg
`which doxygen` template_type_alias.cfg
`which doxygen` template_specialisation.cfg
`which doxygen` enum.cfg
`which doxygen` define.cfg
`which doxygen` interface.cfg
`which doxygen` xrefsect.cfg
`which doxygen` tables.cfg
`which doxygen` cpp_anon.cfg
`which doxygen` cpp_concept.cfg
`which doxygen` cpp_enum.cfg
`which doxygen` cpp_union.cfg
`which doxygen` cpp_function.cfg
`which doxygen` cpp_friendclass.cfg
`which doxygen` cpp_inherited_members.cfg
`which doxygen` cpp_trailing_return_type.cfg
`which doxygen` cpp_constexpr_hax.cfg
`which doxygen` cpp_function_lookup.cfg
`which doxygen` c_file.cfg
`which doxygen` c_struct.cfg
`which doxygen` c_enum.cfg
`which doxygen` c_typedef.cfg
`which doxygen` c_macro.cfg
`which doxygen` c_union.cfg
`which doxygen` membergroups.cfg
`which doxygen` simplesect.cfg
`which doxygen` code_blocks.cfg
`which doxygen` dot_graphs.cfg
`which doxygen` programlisting.cfg
`which doxygen` decl_impl.cfg
`which doxygen` multifile.cfg
`which doxygen` auto.cfg
`which doxygen` class.cfg
`which doxygen` typedef.cfg
make[1]: Leaving directory '/home/hwhsu1231/Repo/testing/breathe/examples/specific'
make -C documentation html
make[1]: Entering directory '/home/hwhsu1231/Repo/testing/breathe/documentation'
sphinx-build -b html -P -d build/doctrees  -v -W -E source build/html
Running Sphinx v7.4.7
Using Doxygen v1.9.4
fatal: No names found, cannot describe anything.
loading translations [en]... locale_dir /home/hwhsu1231/Repo/testing/breathe/documentation/source/locales/en/LC_MESSAGES does not exist
locale_dir /home/hwhsu1231/Repo/testing/breathe/documentation/source/locales/en/LC_MESSAGES does not exist
done
Adding copy buttons to code blocks...
Initializing Spelling Checker 8.0.0
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
locale_dir /home/hwhsu1231/Repo/testing/breathe/documentation/source/locales/en/LC_MESSAGES does not exist
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/application.py", line 292, in __init__
    self._init_builder()
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/application.py", line 366, in _init_builder
    self.events.emit('builder-inited')
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/sphinx/events.py", line 98, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/directives/setup.py", line 114, in doxygen_hook
    doxygen_handle.generate_xml(
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py", line 69, in generate_xml
    project_path = self.process(
  File "/home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py", line 93, in process
    input=" ".join(full_paths),
TypeError: sequence item 0: expected str instance, PosixPath found
> /home/hwhsu1231/Repo/testing/breathe/.venv/lib/python3.10/site-packages/breathe/process.py(93)process()
-> input=" ".join(full_paths),
(Pdb) 
```

</details>

**Comment by hwhsu1231** [comment]
@michaeljones @AA-Turner

Hello, Breathe Maintenance Team.

I’ve observed that the error mentioned in this issue does not occur at the `v4.35.0` tag. 

- The commands I used to build breathe-docs at `main` branch, but **FAILED**:

  ```bash
  git clone --branch=main --depth=1 https://github.com/breathe-doc/breathe.git breathe-main
  cd breathe-main
  git show --no-patch
  conda create --prefix ./.venv --yes
  conda activate ./.venv
  export LANG=en_US.UTF-8
  export PYTHONNOUSERSITE=1
  conda install python=3.12 doxygen=1.9.6 graphviz -c conda-forge --yes
  python -m pip install .[docs]
  make html
  exit
  ```

  [log-build-breathe-docs-main-branch-failed.txt](https://github.com/user-attachments/files/18221310/log-build-breathe-docs-main-branch-failed.txt)

- The commands I used to build breathe-docs at `v4.35.0` tag, and **SUCCEEDED**:

  ```bash
  git clone --branch=v4.35.0 --depth=1 https://github.com/breathe-doc/breathe.git breathe-v4.35.0
  cd breathe-v4.35.0
  git show --no-patch
  conda create --prefix ./.venv --yes
  conda activate ./.venv
  export LANG=en_US.UTF-8
  export PYTHONNOUSERSITE=1
  conda install python=3.12 doxygen=1.9.6 graphviz -c conda-forge --yes
  python -m pip install -r requirements/development.txt
  make html
  ```

  [log-build-breathe-docs-v4-35-0-tag-succeeded.txt](https://github.com/user-attachments/files/18221311/log-build-breathe-docs-v4-35-0-tag-succeeded.txt)

This suggests that something might have gone wrong between the `v4.35.0` tag ([4e9f55e](https://github.com/breathe-doc/breathe/commit/4e9f55eadc91d96ac155a24c3634359b511a82cd)) and the `main` branch ([62695c7](https://github.com/breathe-doc/breathe/commit/62695c7e3eaf1190f7bb02ba7b396daf78da66f4)). Changes between the two commits:

https://github.com/breathe-doc/breathe/compare/4e9f55e...62695c7
